version: "3.4"

services:
  ng:
    container_name: angular-pokemon
    image: angular-pokemon
    build:
      context: .
    ports:
      - 5555:4200
    volumes:
      - ".:/app"
      - "/app/node_modules"
